host = "http://localhost:8000"
secret = "abc123"
requireSecret = true
storeSecretInCookies = true

[[commands]]

name = "YouTube"
command = "yt-dlp"
options = [
  ["--output",         "%(uploader)s - %(title)s - %(id)s"],
  ["--format",         "bestvideo*+bestaudio/best"        ],
  ["--no-overwrites"                                      ],
  ["--sub-langs",      "all,-live_chat"                   ],
  ["--embed-subs"                                         ],
  ["--throttled-rate", "1M"                               ]
]

[[commands]]

name = "General yt-dlp"
command = "yt-dlp"
options = [
  ["--format", "bestvideo*+bestaudio/best"],
  ["--no-overwrites"]
]
